on: 
  workflow_dispatch:
    inputs: 
      environment: 
        description: "Choose environment"
        required: true
        default: "staging"
        type: choice
        options: 
          - staging
          - production

jobs: 
  deploy:
    runs-on: ubuntu_latest
    steps: 
      - name: Deloy application
        run: echo "Deploying the application ..."
